apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: pfx-ambulance-webapi-mongodb-init # @_pfx_@
    files:
      - params/init-db.js
  - name: pfx-ambulance-webapi-config # @_pfx_@
    literals:
      - database=ambulance
      - collection=ambulance

