/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: pfx@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateWaitingListEntry - Saves new entry into waiting list
func CreateWaitingListEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteWaitingListEntry - Deletes specific entry
func DeleteWaitingListEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetWaitingListEntries - Provides the ambulance waiting list
func GetWaitingListEntries(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetWaitingListEntry - Provides details about waiting list entry
func GetWaitingListEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateWaitingListEntry - Updates specific entry
func UpdateWaitingListEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
