/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: pfx@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetConditions - Provides the list of conditions associated with ambulance
func GetConditions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
